### ISSUE TITLE
Replace checkIn code with QR

### ISSUE THREAD

**Issue by HanielDiaz** [SHPEUCF/shpeucfapp#85]
- [x] Generate QR code for each event that has the first 4 characters be the event code and the rest of them be the id of the user who created it
- [ ] Whenever anyone checks in, there should be a log of who's QR code they used to check in.
- [ ] Check-in should be perma-closed an hour after the event time to allow for people forgetting and then go to this issue #97

**Comment by HollandWeaver** [comment]
Could we look into proximity checks through GPS?

**Comment by HanielDiaz** [comment]
The issues with GPS is that it doesn't work well in-doors but maybe we should try doing some testing to see if it's as bad as people say it is. But there are also apps that can spoof your location. A lot of people use them to lie to snapchat or Pokemon Go

**Comment by HollandWeaver** [comment]
Do we want to incentivize people to try and break in and formulate results based off of that?
I'm also curious about the defect rate and how much of our time this is worth as far as value-added is concerned. On the other hand, it's just fun and good practice for computer science practices.

**Comment by HanielDiaz** [comment]
So we definitely don't have the resources to make a state of the art solution, but I feel like this problem is one that's definitely resume worthy in it's own right and a great learning experience regardless of whether it's GPS or barcode or QR code. 

As for defect rate, right now it's very easy to send the code to a friend. The only deterrent we have is that IF the board closes the check-in then it will no allow people to check in even with the code. But the code is open for long amounts of time, making it very easy for someone to check in.

**Comment by HollandWeaver** [comment]
The time aspect definitely addresses the problem to some extent, I'm wondering if a GPS aspect regarding other members' proximity could be of use to ward off the issue of remote location falsification.

Like how blockchain works where the longest chain is deemed the "true" chain? If we were able to affirm locations by running checks with other instances of the app (say you need at least four instances of the app open within 20m of you for the boolean isHere to == true) this might act as a security measure. I'm not educated enough on how GPS spoofing works enough to know if this would offer a solution.

Trying to think one step ahead of if GPS proxied through some list, reject. Since then we have to keep updating that list. Rather, if we could check the validity dynamically this could potentially reduce defects.

**Comment by idelmr** [comment]
Fixed by @esteban737 last year
